#!/usr/bin/env zsh

function prepend-sudo {
    [[ -z $BUFFER ]] && BUFFER=$(fc -ln -1)

    [[ $BUFFER == sudo\ * ]] && return

    BUFFER="sudo $BUFFER"
    zle accept-line
}
zle -N prepend-sudo

function edit-command {
    zle push-input -w
    [[ -z "$BUFFER" ]] && BUFFER=$(fc -ln -1)

    if zle expand-cmd-path; then
        BUFFER="${EDITOR:-vim} ${BUFFER%% *}"
        zle accept-line
    fi
}
zle -N edit-command

function launch-command {
    gnome-terminal -- $BUFFER
}
zle -N launch-command

function foreground {
    zle push-input -w
    BUFFER="fg"
    if [ "$NUMERIC" ]; then
        BUFFER+=" %$NUMERIC"
    fi
    zle accept-line
}
zle -N foreground

bindkey -M viins '^S' prepend-sudo
bindkey -M viins '^E' edit-command
bindkey -M viins '^T' launch-command
bindkey -M viins '^Z' foreground
bindkey -M vicmd '^Z' foreground

bindkey -M vicmd '^H' run-help
bindkey -M viins '^P' up-history
bindkey -M viins '^N' down-history
