#!/usr/bin/env bash

set -eu

cmd=cat
declare -A switch=([bash]=cat [cat]=bash)

while read -r; do
    if [ "$REPLY" = script_begin -a $cmd = cat -o\
         "$REPLY" = script_end -a $cmd = bash ]; then
        $cmd <<< "$buffer"
        unset buffer
        cmd=${switch[$cmd]}
    else
        buffer+="$REPLY"$'\n'
    fi
done < $1 > ${1%.cfc}
