#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later

# TODO: Play sound always on speaker

set -eu

sound=$HOME/.local/share/misc/samsung_s8_tone.mp3

alert_user() {
    loop >/dev/null 2>&1 &
    pid=$!
    zenity --info --title=Timer --text="$* are over."
    kill -9 $pid
}

loop() {
    while [ true ]; do
        ffplay -autoexit -nodisp "$sound"
    done
}

sleep "$@"
alert_user "$@"
