#!/bin/sh

watchdir() {
    inotifywait -qmr \
        -e modify -e moved_to \
        --format "%w%f" "$1" |
        while read filePath; do
            ${2:-echo} "$filePath"
            #if [[ "$filePath" =~ $2 ]]
            #then
            #    eval "$3"
            #fi
        done
}

mktx() {
    cd $(dirname "$1")
    pdflatex --halt-on-error "$1"
    path=$(realpath "$1")
    prefix=${path:0:-4}
    /bin/rm "$prefix.log" "$prefix.aux" "$prefix.out"
}

mktx2() {
    cd $(dirname "$1")
    xelatex --halt-on-error "$1"
    path=$(realpath "$1")
    prefix=${path:0:-4}
    /bin/rm "$prefix.log" "$prefix.aux" "$prefix.out"
}
