#!/bin/bash

unset SXHKD_SHELL DCONF_PROFILE
unset JOURNAL_STREAM IM_CONFIG_PHASE MANAGERPID INVOCATION_ID # systemd environment

shift # Remove '-c'
if [[ "$1" =~ ^\! ]]; then
   .config/sxhkd/switch default
fi

exec $SHELL -c "${1#!}"
