#!/bin/bash


__dot() {
    local comps command=$1 curr="$2" prev="$3" # $1 should always be dot anyways ?
    local subcommands="start stop now tag add link rm status help ls"
    local noargopts="-f --force -v --verbose -h --help"
    if [[ "$prev" =~ link|rm ]]; then
        comps=$(cat /home/aljoschua/.files/conf/.files-list)
    fi
    if ! [[ "$prev" =~ ${subcommands/ /|} ]]; then
        comps="$subcommands"
    fi
    COMPREPLY=($(compgen -W "$comps" -- "$curr"))
    :<<END
    if [ "$COMP_CWORD" = 1 ]; then
        comps="-v $subcommands"
    fi
    if [ "$COMP_CWORD" = 2 ]; then
        case ${COMP_WORDS[1]} in
            -v)
                comps="$subcommands" ;;
            add)
                COMPREPLY=($(compgen -o default -- "$curr")) ;;
            link|remove)
                comps=$(cat /home/aljoschua/.files/conf/.files-list) ;; # does this handle spaces in names ?
            *)
                comps="" ;;
        esac
    fi
    if [ "$COMP_CWORD" = 3 ]; then
        echo ...
    fi
    COMPREPLY=$(compgen -W "$comps" -- "$curr")
END

}
complete -o default dot
