[url "github:"]
    insteadOf = hub:
[url "github-aljoschafrey:aljoschafrey/"]
    insteadOf = hubtub:
[url "git@gitlab.com:"]
    insteadOf = lab:
[url "github:aljoschua/"]
    insteadOf = my:
[url "git@gitlab.tu-berlin.de:"]
    insteadOf = tubold:
[url "git-tub:aljoschafrey/"]
    insteadOf = myt:
[url "git-tub:"]
    insteadOf = tub:
[url "sshgate.tu-berlin.de:x/"]
    insteadOf = gate:
[url "git://git.suckless.org/"]
    insteadOf = sl:
