#!/bin/bash


rendezvous=aljoschafrey@login.fu-berlin.de
rendezvous=aljoschua@e525
tmpfile=/tmp/currentPublicIP


# Maybe use only one connection?
publicIP=$(ssh $rendezvous "echo \$SSH_CONNECTION | cut -d' ' -f1")
if [ ! -e "$tmpfile"  ] || [ $(cat "$tmpfile") != $publicIP ]; then
	ssh $rendezvous "echo `date -Iseconds` $(hostname) $publicIP >> IPs"
fi

echo $publicIP > "$tmpfile"

